version: '3.8'

volumes:
  database_volume:
  static_volume:
  media_volume:

services:

  cadastral_database:
    image: postgres:15-alpine
    volumes:
      - database_volume:/var/lib/postgresql/data/
    env_file:
      - backend/.env

  cadastral_redis:
    image: redis:7.2.1-alpine

  cadastral_external_server:
    build:
      context: external_api
      dockerfile: Dockerfile

  cadastral_backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: backend/.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - cadastral_database
      - cadastral_redis

  cadastral_gateway:
    image: nginx:1.19.3-alpine
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - cadastral_external_server
      - cadastral_backend
