##########################################################################
################################ ENDPOINTS ###############################
##########################################################################

@history = http://127.0.0.1:8000/api/v1/history/

@ping = http://127.0.0.1:8000/api/v1/ping/

@query = http://127.0.0.1:8000/api/v1/query/

@result = http://127.0.0.1:8000/api/v1/result/


##########################################################################
################################ REQUESTS ################################
##########################################################################

###
GET {{history}} HTTP/1.1
Content-Type: application/json

{
    "number": "12:12:123456:12"
}

###
POST {{ping}} HTTP/1.1

###
GET {{result}} HTTP/1.1
Content-Type: application/json

{
    "number": "12:12:123456:12"
}

###
POST {{query}} HTTP/1.1
Content-Type: application/json

{
    "number": "12:12:123456:12",
    "latitude": "12.1",
    "longitude": "12.123456"
}
